.catalog:
  name: "ConcourseCI"
  version: "3.10.0-b"
  description: "Deploy ConcourseCI In Rancher"
  uuid: concourse-0
  minimum_rancher_version: v1.0.0
  questions:
    - variable: CONCOURSE_EXTERNAL_ADDR
      description: "Address of Concourse Service"
      label: "Concourse External Address"
      type: "string"
      required: true
      default: "172.19.8.101"

concourse-db:
  scale: 1
concourse-web:
  scale: 1
concourse-worker:
  scale: 1
concourse-datavolume:
  scale: 1
